openapi: 3.0.0
info:
  title: Calculator API
  version: 1.0.0
  description: API for calculator application

servers:
  - url: /api
    description: API server

paths:
  /hello/:
    $ref: './paths/hello.yml'
